print('Enter the name of a cat 1:')
cat_name_01 = input()
print('Enter the name of a cat 2:')
cat_name_02 = input()
print('Enter the name of a cat 3:')
cat_name_03 = input()
print('Enter the name of a cat 4:')
cat_name_04 = input()
print('The cat names are: ')
print(cat_name_01, cat_name_02, cat_name_03, cat_name_04)
